spring:
  application:
    name: notification
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8085
rabbitmq:
  exchange:
    name: order.exchange
  queue:
    name:  order.queue
  routing:
    key: order.tracking